# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: shellcheck
  - repo: local
    hooks:
      - id: run_checks
        name: Run Checks
        entry: run_checks.sh
        language: script
        pass_filenames: false
